# Generated by Django 2.2.7 on 2019-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jumia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jumia',
            name='url',
        ),
    ]
