# Generated by Django 2.2.7 on 2019-11-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191127_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfecto',
            old_name='url',
            new_name='link',
        ),
    ]
